// Generated by CoffeeScript 1.9.3
(function() {
  var app, brown, express;

  express = require('../node_modules/express');

  brown = require('../index.coffee');

  app = new express();

  app.engine('html', brown.__express);

  app.set('view engine', 'html');

  app.set('views', __dirname + "/view");

  brown.data = {
    foo: "hiiiii",
    bar: {
      flop: function(str) {
        return "thats " + str;
      }
    }
  };

  app.get('/', function(req, res) {
    return res.render('index.html', {
      foo: "foo"
    });
  });

  app.listen(3000);

}).call(this);
